### ISSUE TITLE
Flood Error

### ISSUE THREAD

**Issue by tcarlsen** [StyraHem/ShellyForHASS#115]
Hey there. I having problems with adding my Flood. H&T sensor was no problem.

Log:
```
TypeError: __init__() missing 1 required positional argument: 'info_type'
2019-12-10 18:06:40 ERROR (CoAP) [pyShelly] Error receiving UDP, __init__() missing 1 required positional argument: 'info_type', Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 318, in _coap_loop
    ipaddr, code, payload)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 161, in _update_block
    Block(self, block_id, device_type, ipaddr, code)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 36, in __init__
    self._setup()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 205, in _setup
    self._add_device(Flood(self))
  File "/usr/local/lib/python3.7/site-packages/pyShelly/sensor.py", line 40, in __init__
    super(Flood, self).__init__(block, 23, 'flood')
  File "/usr/local/lib/python3.7/site-packages/pyShelly/sensor.py", line 31, in __init__
    super(BinarySensor, self).__init__(block, pos, device_type)
TypeError: __init__() missing 1 required positional argument: 'info_type'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 318, in _coap_loop
    ipaddr, code, payload)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 161, in _update_block
    Block(self, block_id, device_type, ipaddr, code)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 36, in __init__
    self._setup()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 205, in _setup
    self._add_device(Flood(self))
  File "/usr/local/lib/python3.7/site-packages/pyShelly/sensor.py", line 40, in __init__
    super(Flood, self).__init__(block, 23, 'flood')
  File "/usr/local/lib/python3.7/site-packages/pyShelly/sensor.py", line 31, in __init__
    super(BinarySensor, self).__init__(block, pos, device_type)
TypeError: __init__() missing 1 required positional argument: 'info_type'
```

**Comment by sfanicola** [comment]
same here... any solutions?

**Comment by brighthouse** [comment]
I have same issue with release 0.1.5 and discovery of Shelly Flood. Log entries looks same.
On release 0.1.0 Flood is discovered by plugin and work OK. After upgrade to release higher than 0.1.0 Flood is no more discovered by system.

**Comment by zsbobbob** [comment]
I have the same issue, can not discover the flood sensor. I have the same log error:

Error receiving CoAP UDP, __init__() missing 1 required positional argument: 'info_type', Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 169, in _loop
    ipaddr, 'CoAP-message', payload)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 181, in update_block
    Block(self, block_id, device_type, ipaddr, src)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 43, in __init__
    self._setup()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 207, in _setup
    self._add_device(Flood(self))
  File "/usr/local/lib/python3.7/site-packages/pyShelly/sensor.py", line 40, in __init__
    super(Flood, self).__init__(block, 23, 'flood')
  File "/usr/local/lib/python3.7/site-packages/pyShelly/sensor.py", line 31, in __init__
    super(BinarySensor, self).__init__(block, pos, device_type)
TypeError: __init__() missing 1 required positional argument: 'info_type'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/coap.py", line 169, in _loop
    ipaddr, 'CoAP-message', payload)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 181, in update_block
    Block(self, block_id, device_type, ipaddr, src)
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 43, in __init__
    self._setup()
  File "/usr/local/lib/python3.7/site-packages/pyShelly/block.py", line 207, in _setup
    self._add_device(Flood(self))
  File "/usr/local/lib/python3.7/site-packages/pyShelly/sensor.py", line 40, in __init__
    super(Flood, self).__init__(block, 23, 'flood')
  File "/usr/local/lib/python3.7/site-packages/pyShelly/sensor.py", line 31, in __init__
    super(BinarySensor, self).__init__(block, pos, device_type)
TypeError: __init__() missing 1 required positional argument: 'info_type

**Comment by hakana** [comment]
Found, will be fixed in next release

**Comment by sfanicola** [comment]
Can you tell us where the error is? Or when will be released the next update?

**Comment by MTrab** [comment]
Any ETA on this new release?

**Comment by chemelli74** [comment]
> Any ETA on this new release?

Hi @MTrab, please retest with latest build 0.1.6b9.

Thank you,

Simone

**Comment by chemelli74** [comment]
i all, just to inform that after 3 weeks of inactivities on very old thread, I'll proceed to close them.
If later one someone verify that the issue is still there, a new issue need to be opened.

Thank you,

Simone

**Comment by MTrab** [comment]
Still awaiting a new version available for install - so no activity is due to no new versions.

**Comment by MTrab** [comment]
![Shelly](https://user-images.githubusercontent.com/14296463/73462339-f2193c80-437b-11ea-893c-8b11fe2e560f.PNG)

**Comment by chemelli74** [comment]
> Still awaiting a new version available for install - so no activity is due to no new versions.

Hi @MTrab, as I told you please enable beta on HACS and install 0.1.6b9. You can see a "last updated: 5 days ago".

Thank you,

Simone

**Comment by MTrab** [comment]
No betas available - I have tried installing the master 5 days ago, nothing changed by doing that.
![Shelly_2](https://user-images.githubusercontent.com/14296463/73465344-8c7b7f00-4380-11ea-81d3-0720e4d86c72.PNG)

**Comment by chemelli74** [comment]
You should first enable beta. You don't know how ? Just click on the right side on the 3 lines menu.
Mine shows disable but yours should show enable:

![image](https://user-images.githubusercontent.com/57354320/73465643-f3993380-4380-11ea-9285-4b20ed8749fd.png)

Simone

**Comment by MTrab** [comment]
Oh sorry - I have never noticed that option - will test right away.

**Comment by tcarlsen** [comment]
I still think it’s odd to close a issue that haven’t been fixed in a stable version. 
Saying the bug is fixed in beta is fine, but as long as it’s still there in stable release makes this issue valid

**Comment by chemelli74** [comment]
> I still think it’s odd to close a issue that haven’t been fixed in a stable version.
> Saying the bug is fixed in beta is fine, but as long as it’s still there in stable release makes this issue valid

Hi, I can get your point but we need to keep the focus to issues that are still active with latest code.
After all, why not upgrade to latest beta if you have a issue ? ;-)
Take also care that the project is developped using peoplpe's free time.

Thank you for your understanding,

Simone

**Comment by tcarlsen** [comment]
> > I still think it’s odd to close a issue that haven’t been fixed in a stable version.
> > Saying the bug is fixed in beta is fine, but as long as it’s still there in stable release makes this issue valid
> 
> Hi, I can get your point but we need to keep the focus to issues that are still active with latest code.
> After all, why not upgrade to latest beta if you have a issue ? ;-)
> Take also care that the project is developped using peoplpe's free time.
> 
> Thank you for your understanding,
> 
> Simone

I do respect that it takes time. I have done open source myself so I’m not trying to rush anything here. But using beta is normally something you do if you’re okay with minor issues and crashes. 

If you believe just use beta. Why not just release in stable if no risk??

Maybe use label to indicate that the issue is fixed but still being tested aka beta.

**Comment by MTrab** [comment]
> Hi, I can get your point but we need to keep the focus to issues that are still active with latest code.
> After all, why not upgrade to latest beta if you have a issue ? ;-)
> Take also care that the project is developped using peoplpe's free time.

We all develop during our spare time. It's not the right way to close an issue until a fix/upgrade is released to stable.
That way you'll just risk getting more issues opened on the same error.

Let "beta solved" issues remain open until a stable release is ready.

**Comment by MTrab** [comment]
That said - I can't upgrade to beta.
No matter how many times I press upgrade, 0.1.5 remains the one installed.

**Comment by chemelli74** [comment]
> That said - I can't upgrade to beta.
> No matter how many times I press upgrade, 0.1.5 remains the one installed.

witch version of HA and HACS you have ?
did you have 0.1.6b9 in the list ? did you manually selected it before hitting upgrade ?

Simone

**Comment by hakana** [comment]
@HTrab You need to enable beta in HACS.
![image](https://user-images.githubusercontent.com/1168654/73522826-b62cb880-4409-11ea-947d-8d2e7989ce04.png)

**Comment by zsbobbob** [comment]
I have 0.1.6 beta 9 and working fine. The binary sensor and temperature added and also some additional sensors based on the config file.
Thanks

**Comment by MTrab** [comment]
Finally got it to install - and it works now.
